# Generated by Django 4.2.6 on 2023-10-18 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shopping", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default=None, max_length=30)),
                (
                    "image",
                    models.ImageField(default=None, upload_to="imagestore/banner"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NewCart",
            fields=[
                ("cartid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carts",
                        to="shopping.userdetail",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="product",
            name="variants",
        ),
        migrations.AddField(
            model_name="category",
            name="offer_percentage",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="order",
            name="variant",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="offer_percentage",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="price_after_offer",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="order",
            name="ordertype",
            field=models.CharField(
                choices=[
                    ("Cash on delivery", "Cash on delivery"),
                    ("Online Payment", "Online Payment"),
                    ("Razorpay", "Razorpay"),
                    ("Wallet", "Wallet"),
                ],
                default="Cash on delivery",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="variant",
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("balance", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shopping.userdetail",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "type",
                    models.CharField(default="Transfer", max_length=200, null=True),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shopping.wallet",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NewWishlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shopping.userdetail",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shopping.productvariant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coupon_code", models.CharField(max_length=30)),
                ("is_active", models.BooleanField(default=False)),
                ("discount_price", models.IntegerField(default=0)),
                ("minimum_amount", models.IntegerField(default=500)),
                ("applied", models.BooleanField(default=False)),
                (
                    "description",
                    models.CharField(default="Sample", max_length=200, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shopping.userdetail",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NewCartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="shopping.newcart",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shopping.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shopping.userdetail",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shopping.productvariant",
                    ),
                ),
            ],
            options={
                "unique_together": {("cart", "user", "variant")},
            },
        ),
    ]
