# Generated by Django 4.1.7 on 2023-05-12 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewCart',
            fields=[
                ('cartid', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='shopping.userdetail')),
            ],
        ),
        migrations.CreateModel(
            name='NewCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shopping.cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.userdetail')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.variant')),
            ],
            options={
                'unique_together': {('cart', 'user', 'variant')},
            },
        ),
    ]
