# Generated by Django 4.1.7 on 2023-05-12 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_newcart_newcartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shopping.newcart'),
        ),
    ]
