# Generated by Django 4.1.7 on 2023-05-12 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_alter_newcartitem_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcartitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping.product'),
        ),
    ]
