# Generated by Django 4.2.1 on 2023-05-13 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_newcartitem_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=30)),
                ('image', models.ImageField(default=None, upload_to='imagestore/banner')),
            ],
        ),
    ]
