# Generated by Django 4.2.1 on 2023-05-15 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0006_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='variants',
        ),
    ]
