# Generated by Django 4.2.1 on 2023-05-16 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_remove_product_variants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newcartitem',
            name='price',
        ),
        migrations.AlterField(
            model_name='newcartitem',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.productvariant'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='variant',
            field=models.CharField(max_length=50),
        ),
    ]
