# Generated by Django 4.2.1 on 2023-05-16 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0008_remove_newcartitem_price_alter_newcartitem_variant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewWishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shopping.userdetail')),
                ('variant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shopping.productvariant')),
            ],
        ),
    ]
