# Generated by Django 4.2.1 on 2023-05-20 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0012_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='offer_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
