# Generated by Django 4.2.1 on 2023-05-20 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0013_category_offer_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='price_befor_offer',
            field=models.IntegerField(default=0),
        ),
    ]
