# Generated by Django 4.2.1 on 2023-05-20 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0014_productvariant_price_befor_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
