# Generated by Django 4.1.7 on 2023-05-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0015_product_offer_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='variant',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordertype',
            field=models.CharField(choices=[('Cash on delivery', 'Cash on delivery'), ('Paypal', 'Paypal'), ('Razorpay', 'Razorpay'), ('Paid From Your Wallet', 'Paid From Your Wallet')], default='Cash on delivery', max_length=50),
        ),
    ]
