# Generated by Django 4.1.7 on 2023-05-31 03:58

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0016_order_variant_alter_order_ordertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '120x120', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordertype',
            field=models.CharField(choices=[('Cash on delivery', 'Cash on delivery'), ('Online Payment', 'Online Payment'), ('Razorpay', 'Razorpay'), ('Paid From Your Wallet', 'Paid From Your Wallet')], default='Cash on delivery', max_length=50),
        ),
    ]
