# Generated by Django 4.1.7 on 2023-05-31 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0017_image_cropping_alter_order_ordertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='cropping',
        ),
    ]
