# Generated by Django 4.1.7 on 2023-05-31 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0019_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
