# Generated by Django 4.1.7 on 2023-05-31 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0021_alter_order_ordered_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='description',
            field=models.CharField(default='Transfer', max_length=200, null=True),
        ),
    ]
