# Generated by Django 4.1.7 on 2023-05-31 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0022_wallet_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='description',
        ),
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(default='Transfer', max_length=200, null=True),
        ),
    ]
