# Generated by Django 4.1.7 on 2023-05-31 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0023_remove_wallet_description_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateField(auto_now_add=True),
        ),
    ]
