# Generated by Django 4.1.7 on 2023-06-01 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0025_alter_transaction_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='price_befor_offer',
            new_name='price_after_offer',
        ),
    ]
